// apps/ui/src/components/ProductCard.tsx
import type { FunctionComponent } from 'react'

const ProductCard: FunctionComponent = () => {
  return (
    <div className="rounded-lg bg-white shadow-[-2px_2px_15px_-1px_rgba(113,_113,_113,_0.12)] overflow-hidden flex flex-col items-end justify-start py-[0.889rem] pr-[0.889rem] pl-[0rem] box-border gap-[0.861rem] w-auto [align-self:unset] h-auto text-left text-[0.889rem] text-black font-web-button-lg hover:bg-white hover:flex hover:w-auto hover:[align-self:unset] hover:h-auto hover:flex-col hover:gap-[15.5px] hover:items-end hover:justify-start hover:rounded-lg hover:py-4 hover:pr-4 hover:pl-0 hover:box-border hover:shadow-[-2px_2px_15px_-1px_rgba(113,_113,_113,_0.12)]">
      <div className="self-stretch h-[10.556rem] relative flex w-auto gap-[0rem] items-start justify-start [transform:rotate(0deg)] hover:flex hover:self-stretch hover:w-auto hover:h-[190px] hover:gap-[0px] hover:items-start hover:justify-start hover:[transform:rotate(0deg)]">
        <div className="absolute top-[0rem] left-[0.889rem] flex flex-row items-end justify-start pt-[0.778rem] pb-[0.833rem] pr-[0rem] pl-[1.056rem] box-border gap-[0.444rem] w-auto [align-self:unset] h-auto hover:flex hover:w-auto hover:[align-self:unset] hover:h-auto hover:flex-row hover:gap-[8px] hover:items-end hover:justify-start hover:pt-3.5 hover:pb-[15px] hover:pr-0 hover:pl-[19px] hover:box-border">
          <img
            className="h-[8.944rem] w-[12.056rem] relative rounded-lg overflow-hidden shrink-0 object-contain flex gap-[0rem] hover:flex hover:w-[217px] hover:h-[161px] hover:gap-[0px] hover:rounded-lg"
            alt=""
            src="/images/image-15@2x.png"
          />
          <div className="h-[4.778rem] flex flex-col items-start justify-start w-auto [align-self:unset] gap-[0rem] [transform:rotate(0deg)] hover:flex hover:w-auto hover:[align-self:unset] hover:h-[86px] hover:flex-col hover:gap-[0px] hover:items-start hover:justify-start hover:[transform:rotate(0deg)]">
            <div className="flex flex-col items-center justify-start w-auto [align-self:unset] h-auto gap-[0.444rem] hover:flex hover:w-auto hover:[align-self:unset] hover:h-auto hover:flex-col hover:gap-[8px] hover:items-center hover:justify-start">
              <div className="w-[0.667rem] h-[0.667rem] relative rounded-[50%] bg-white box-border flex border-[0.3px] border-solid border-neutral-gray-444444 hover:bg-white hover:flex hover:w-3 hover:h-3 hover:box-border hover:border-[0.3px] hover:border-solid hover:border-neutral-gray-444444" />
            </div>
          </div>
        </div>
        <button className="cursor-pointer [border:none] py-[0.222rem] px-[0.333rem] bg-bisque absolute top-[0rem] left-[0rem] rounded-tl-none rounded-tr-lg rounded-br-lg rounded-bl-none overflow-hidden flex flex-row items-start justify-start box-border w-auto [align-self:unset] h-auto gap-[0.556rem] z-[1] hover:bg-bisque hover:flex hover:w-auto hover:[align-self:unset] hover:h-auto hover:flex-row hover:gap-[10px] hover:items-start hover:justify-start hover:rounded-tl-none hover:rounded-tr-lg hover:rounded-br-lg hover:rounded-bl-none hover:py-1 hover:px-1.5 hover:box-border">
          <div className="relative text-[0.889rem] leading-[1.333rem] font-light font-web-button-lg text-secondary text-left flex min-w-[37] hover:font-light hover:font-web-button-lg hover:text-base hover:leading-[24px] hover:text-left hover:text-secondary hover:flex hover:min-w-[37]">
            -10%
          </div>
        </button>
      </div>
      <img
        className="w-[14.222rem] h-[0.056rem] relative flex box-border border-[1px] border-solid border-darkslategray-400 hover:flex hover:w-64 hover:h-px hover:box-border hover:border-[1px] hover:border-solid hover:border-darkslategray-400"
        alt=""
        src="/icons/line-3-1.svg"
      />
      <div className="w-[14.222rem] flex flex-col items-start justify-start gap-[0.889rem] h-auto hover:flex hover:w-64 hover:h-auto hover:flex-col hover:gap-[16px] hover:items-start hover:justify-start">
        <div className="self-stretch h-[2.111rem] relative leading-[1.333rem] font-light flex items-center overflow-hidden text-ellipsis whitespace-nowrap shrink-0 w-auto hover:font-light hover:font-web-button-lg hover:text-base hover:leading-[24px] hover:text-left hover:text-black hover:flex hover:self-stretch hover:w-auto hover:h-[38px]">
          Airpods pro2
        </div>
        <div className="self-stretch flex flex-row items-end justify-between gap-[0rem] [row-gap:20px] w-auto h-auto text-[0.778rem] text-neutral-gray-717171 hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-row hover:gap-[0px] hover:items-end hover:justify-between hover:[row-gap:20px]">
          <div className="w-[7.111rem] flex flex-col items-center justify-start h-auto gap-[0rem] hover:flex hover:w-32 hover:h-auto hover:flex-col hover:gap-[0px] hover:items-center hover:justify-start">
            <div className="self-stretch flex flex-col items-center justify-start w-auto h-auto gap-[0rem] hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-col hover:gap-[0px] hover:items-center hover:justify-start">
              <div className="self-stretch relative [text-decoration:line-through] flex whitespace-nowrap w-auto hover:font-web-button-lg hover:text-sm hover:text-left hover:text-neutral-gray-717171 hover:flex hover:self-stretch hover:w-auto hover:whitespace-nowrap">
                $ 285.08
              </div>
              <div className="self-stretch relative text-[1rem] font-light text-black flex whitespace-nowrap w-auto hover:font-light hover:font-web-button-lg hover:text-lg hover:text-left hover:text-black hover:flex hover:self-stretch hover:w-auto hover:whitespace-nowrap">
                $274.04
              </div>
            </div>
          </div>
          <div className="w-[7.111rem] flex flex-row items-center justify-end h-auto gap-[0.889rem] text-[0.889rem] text-primary-primary-500 hover:flex hover:w-32 hover:h-auto hover:flex-row hover:gap-[16px] hover:items-center hover:justify-end">
            <div className="flex flex-row items-center justify-end gap-[0.111rem] w-auto [align-self:unset] h-auto hover:flex hover:w-auto hover:[align-self:unset] hover:h-auto hover:flex-row hover:gap-[2px] hover:items-center hover:justify-end">
              <img
                className="h-[1.333rem] w-[1.333rem] relative rounded-11xs-2 bg-primary-primary-500 flex hover:bg-primary-primary-500 hover:flex hover:w-6 hover:h-6 hover:rounded-11xs-2"
                alt=""
                src="/icons/star.svg"
              />
              <div className="relative font-medium flex min-w-[25] hover:font-medium hover:font-web-button-lg hover:text-base hover:text-left hover:text-primary-primary-500 hover:flex hover:min-w-[25]">
                4.2
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default ProductCard

// apps/storefront/src/components/solid/ProductCard.tsx
/** @jsxImportSource solid-js */
import type { Component } from 'solid-js'

export type ProductCardType = {
  className?: string;
  title?: string;
  lastPrice?: string;
  newPrice?: string;
  emptyStarIcon?: string;
  discountAmount?: string;
  showProductCardColorPalette?: boolean;
  showProductCardColorSwatches?: boolean;
  showExtraColor?: boolean;

  /** Style props */
  propBackgroundImage?: string;
  propPadding?: number;
  propBackgroundColor?: string;
  propBackgroundColor1?: string;
  propBackgroundColor2?: string;
  propMinWidth?: number;
  propWidth?: number;
  propHeight?: number;
  propFlex?: string;
  propDisplay?: string;
};

const ProductCard: Component<ProductCardType> = ({
  className = "",
  title,
  lastPrice,
  newPrice,
  emptyStarIcon,
  discountAmount,
  showProductCardColorPalette,
  showProductCardColorSwatches,
  showExtraColor,
  propBackgroundImage,
  propPadding,
  propBackgroundColor,
  propBackgroundColor1,
  propBackgroundColor2,
  propMinWidth,
  propWidth,
  propHeight,
  propFlex,
  propDisplay,
}) => {
  const imageStyle = {
    backgroundImage: propBackgroundImage,
    padding: propPadding,
  };

  const productCardColorPaletteStyle = {
    backgroundColor: propBackgroundColor,
  };


  const productCardColorSwatchesStyle = {
    backgroundColor: propBackgroundColor1,
  };

  const productCardColorSamplesStyle = {
    backgroundColor: propBackgroundColor2,
  };

  const extraColorStyle = {
    minWidth: propMinWidth,
    width: propWidth,
  };

  const discountAmountStyle = {
    height: propHeight,
    flex: propFlex,
    display: propDisplay,
  };

  return (
    <div
      class={`shadow-[-2px_2px_15px_-1px_rgba(113,_113,_113,_0.12)] rounded-lg bg-white overflow-hidden flex flex-col items-start justify-start p-4 gap-[15.5px] z-[19] text-left text-base text-neutral-gray-505050 font-web-button-lg ${className}`}
    >
      <div
        class="self-stretch flex flex-row items-start justify-end py-[55.5px] px-0 bg-[url('/image1@3x.png')] bg-cover bg-no-repeat bg-[top] text-center"
        style={imageStyle}
      >
        <div class="h-[161px] w-[217px] relative rounded-lg overflow-hidden shrink-0 hidden" />
        <div class="flex flex-col items-start justify-start gap-[8px]">
          {showProductCardColorPalette && (
            <div
              class="w-3 h-3 relative rounded-[50%] bg-dimgray box-border border-[0px] border-solid border-neutral-gray-444444"
              style={productCardColorPaletteStyle}
            />
          )}
          {showProductCardColorSwatches && (
            <div
              class="w-3 h-3 relative rounded-[50%] bg-floralwhite box-border border-[0px] border-solid border-neutral-gray-444444"
              style={productCardColorSwatchesStyle}
            />
          )}
          <div
            class="w-3 h-3 relative rounded-[50%] bg-lightsteelblue-200 box-border border-[0px] border-solid border-neutral-gray-444444"
            style={productCardColorSamplesStyle}
          />
          {showExtraColor && (
            <div
              class="relative font-medium inline-block min-w-[11px]"
              style={extraColorStyle}
            >
              +
            </div>
          )}
        </div>
      </div>
      <img
        class="self-stretch h-px relative max-w-full overflow-hidden shrink-0"
        alt=""
        src="/line-3.svg"
      />
      <div class="self-stretch flex flex-col items-start justify-start gap-[16px] text-black">
        <div class="self-stretch relative leading-[24px] font-light [display:-webkit-inline-box] items-center overflow-hidden text-ellipsis [-webkit-line-clamp:2] [-webkit-box-orient:vertical]">
          {title}
        </div>
        <div class="self-stretch flex flex-row items-end justify-between gap-[0px] [row-gap:20px] text-sm text-neutral-gray-717171 mq450:flex-wrap">
          <div class="w-32 flex flex-col items-center justify-start">
            <div class="self-stretch flex flex-col items-center justify-start">
              <div class="self-stretch h-[17px] relative [text-decoration:line-through] hidden whitespace-nowrap">
                {lastPrice}
              </div>
              <div class="self-stretch relative text-lg font-light text-black whitespace-nowrap">
                {newPrice}
              </div>
            </div>
          </div>
          <div class="w-32 flex flex-row items-center justify-end text-base text-primary-primary-500">
            <div class="flex flex-row items-center justify-end gap-[2px]">
              <img
                class="h-6 w-6 relative rounded-11xs-2"
                alt=""
                src="/star-icon.svg"
              />
              <div class="relative font-medium inline-block min-w-[25px]">
                {emptyStarIcon}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="w-[49px] rounded-tl-none rounded-tr-lg rounded-br-lg rounded-bl-none bg-primary-secondary-secondary-100 overflow-hidden hidden flex-row items-center justify-start py-1 px-1.5 box-border text-secondary">
        <div
          class="relative leading-[24px] font-light"
          style={discountAmountStyle}
        >
          {discountAmount}
        </div>
      </div>
    </div>
  );
};

export default ProductCard;
